name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

#      - name: Lint code
#        run: task yarn:lint:check
